### ISSUE TITLE
Inventory.txt - Hirelings

### ISSUE THREAD

**Issue by kainabel666** [eezstreet/d2rlint#1]
Test NumericBounds for inventory.txt needs to allow Hierling2 row to be -1 (rule checks for <0)

**Comment by eezstreet** [comment]
On which column?

**Comment by kainabel666** [comment]
Ok gridx and gridy
 
 
  On Mon, Mar 28, 2022 at 1:04 AM, ***@***.***> wrote:   


On which column?
